### PR TITLE
RTL Text Support

### LINKED ISSUE #21: Support for RTL in the editor
Hi,

I am on macOS Catalina, 10.15.4, running Standard Notes (extended) 3.4.1. I am using this editor as my default editor in Standard Notes, and I see no support for RTL.

Here is how RTL is treated in the editor today:

Screen Shot 2020-05-24 at 9 49 35 PM

If you see https://github.com/standardnotes/desktop/issues/81 you'll find examples of what it should look like. This is an issue for [all RTL languages](https://en.wikipedia.org/wiki/Right-to-left#Current_scripts). The example included is from Arab-160/Aran-161 and specifically uses Persian writing.

Thanks for the great work.

### PR DESCRIPTION
**Pull request by ningsongshen**
Preliminary solution to fix #21, prototype working but not compiled into dist.js.

I found a [plugin](https://github.com/virtser/summernote-rtl-plugin) available for summernote that allows one to switch between RTL and LTR. I think it would be a good solution because it gives user flexibility to choose the direction of text (within a note). It's also been tried and tested so there shouldn't be any major issues. @mobitar any thoughts?

### CODE REVIEW

**Comment by atmoio** [comment]
Before we go with the plugin approach (which adds a lot of new code we can't really attest to), have we tried alternatives, like this:

- https://github.com/summernote/summernote/issues/1746#issuecomment-427495588
- https://github.com/summernote/summernote/issues/1746#issuecomment-221250548
- https://github.com/summernote/summernote/commit/a54c4c0a6b421ce14c7ab88da3eaccd83d039c80#diff-29435a054501beb00e7db4e710e7c74dR24

**Comment by ningsongshen** [comment]
I did try those approaches yesterday, but they seem to change the direction for the entire note. But looking deeper I thought of another way to do it:

Summernote wraps any RTL text in a span tag, but those are not block, so it does nothing. I added a callback onChange to set the parents of any RTL span tags to RTL. 

There is one issue to be fixed: adding LTR text after RTL text is inserted seems to stay RTL. Will look further into it.

**Comment by ningsongshen** [comment]
A simpler solution appeared in my mind today (after considering the examples)! Adding HTML attribute dir=auto to all text elements will automatically support LTR and RTL. But it must be applied to each block element onChange so that LTR and RTL can be supported in the same note.

**Comment by atmoio** [comment]
Nice work!

**Pull request merged**
