### PR TITLE
chore: update npm dependencies

### LINKED ISSUE #27: Upgrade dependencies
Via `ncu`.

### PR DESCRIPTION
**Pull request by ningsongshen**
Update dependencies and closes #27 

There seems to be an issue with the dropdowns. I think it has to do the new Babel because I tried updating Bootstrap individually and nothing broke.

### CODE REVIEW

**Comment by atmoio** [comment]
> There seems to be an issue with the dropdowns. 

Might be jquery related..

**Comment by ningsongshen** [comment]
Ok so I think I found the source of the error, and yes, it is in jQuery. It should be resolved by updating summernote (which also uses jQuery) to 0.8.18. 

Here is the relevant merged PR: https://github.com/summernote/summernote/pull/3720

What would be the best way to go about this? Currently we use a submodule with a fork of summernote here: https://github.com/mobitar/summernote

We need to pull from the summernote repository, but I am wondering if a fork is necessary at all.

**Comment by atmoio** [comment]
A fork may not be necessary. The reason it was originally necessary was one main reason: https://github.com/standardnotes/plus-editor/blob/master/src/main.js#L98

The upstream did not provide this functionality. This functionality allows the editor to reset it's history, so that ctrl + z doesn't trigger an undo when the note changes. So without this, if a user has two Plus Editor notes A and B, and switches from A to B, then presses ctrl + z to undo by accident, it would wipe out the note, because the editor thought it was just an editing change.

With this line above, it resets the history stack, so pressing undo has no effect.

As long as you can verify that this functionality is available without a fork, then we should be ok with having no fork.

**Comment by ningsongshen** [comment]
Today I tested out the editor with the updated summernote (spent some time struggling with submodules and forks and branches and merging...), and I think that changing the note does reset the editor history, which is good. The dropdown bug is also fixed.

I also looked through the summernote code and found this in the master branch: https://github.com/summernote/summernote/blob/master/src/js/base/editing/History.js#L50 which I believe is the exact function you described.

So I think we would be okay without a fork, we just have to make sure that the submodule is linked to a specific commit so that any upstream changes can be reviewed.

Or, I could try updating the fork and keeping the status quo, which might give us a bit more control over any changes. Btw, would mobitar/summernote be better maintained under standardnotes? I can't seem to create a branch if it's not in the standardnotes repository.

**Comment by ningsongshen** [comment]
Include option to disable url shortening, fixes standardnotes/forum#1011

**Comment by atmoio** [comment]
Ok cool, in that case, we should just ditch the submodule and use the npm package instead 👍

**Comment by atmoio** [comment]
> Include option to disable url shortening

I would keep these two PRs separate. PRs should handle only one thing.

**Pull request merged**
