### PR TITLE
Fix cursor colour in code view

### PR DESCRIPTION
**Pull request by ningsongshen**
Fixes the second issue here: https://app.asana.com/0/1178618677234188/1174395765556557/f

### CODE REVIEW

**Comment by atmoio** [comment]
I would first make a PR addressing any code formatting improvements that doesn't impact functionality/UI at all. Then make a separate PR with just the UI change. This way, the two remain independent. We can revert one or the other without having to revert both. For example if something goes wrong with this cursor change, we would want to undo it, without losing all the formatting improvements we made. Also, it's very hard to see what exactly changed in this PR.

**Comment by atmoio** [comment]
You know what, sorry, just saw your other PR :) I believe you did just that. Will review that first.

**Comment by atmoio** [comment]
Ok please pull master into here and I think that should help.

**Comment by ningsongshen** [comment]
Oops I think it may have been a bit unclear because I created this branch off of clean-code so the commits are here too. I'll add a comment next time.

**Comment by ningsongshen** [comment]
Merged master :+1: 

Explanation for fix: The code view background is always black, no matter the theme, so a light-coloured cursor is ideal.

**Comment by atmoio** [comment]
Looks good. I suppose the real solution would be to eventually just theme the code view with StyleKit. But this is a good start.

**Pull request merged**
